spring:
  application:
    name: event-registration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/event-registration-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080